(define (get-esh-cmds)
  (cdr (car (get-conf 'esh))))

(define (start-esh data oret-data)
  (let* ((len (length command-line-arguments)) 
         (arg-2nd (get-arg-2nd)))
    (if (string=? "" arg-2nd)
      (display "arg ned")
      (for-each (lambda (x)
                  (let* ((name (get-conf-str1 x))
                         (cmds (cdr x)))
                    (if (string=? name arg-2nd)
                      (for-each (lambda (cmd)
                                  (runcmd cmd))
                                cmds))))
                (get-esh-cmds)))))

(define (esh-list-cmds d od)
  (for-each (lambda (x) 
              (cout (car x)))
            (get-esh-cmds)))

(define (bakup-mdb d od)
  (let* ((dir "/rt/bakup/")
         (dir1 (string-append dir (substring (run/string (date +%Y%m%d)) 0 8)))
         (tar_name (string-append dir1 ".tgz"))
         (host (get-argn 3))
         (db (get-argn 4))
         (user (get-argn 5))
         (pwd (get-argn 6)))
    (if (file-not-exists? dir) 
      (run (mkdir -p ,dir)))
    (run (mongodump -h ,host -d ,db -u ,user -p ,pwd -o ,dir1))
    (run (tar cvzf ,tar_name ,dir1))))

(define (esh data oret-data)
  (get-opt 
    `(
      (--list         -l     " list cmds                 "  ,esh-list-cmds)
      (--backup-mdb   -      " backup mangolab db        "  ,bakup-mdb)
      (--default      -      " default action            "  ,start-esh)
      (--help         -h     " bprint this usage message "  ,get-opt-usage))))
